services:
  app:
    container_name: task-manager-backend
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: your-db-password
      DB_PORT: 3306
      DB_DATABASE: your-db-name
    depends_on:
      - mysql-db